@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package boblovespi.factoryautomation.api.capability;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;